#!/bin/bash
#
# Before running this script, install Ubuntu 12.04 LTS with OpenSSH.
# Manually setup the network interface(s) and SSH authorized_keys (disable password login).
#
# Run this script with SUDO
# sudo ./ubuntu-12-04

apt-get update
apt-get -y upgrade

apt-get -y install apache2-mpm-worker
apt-get -y install git
apt-get -y install htop
apt-get -y install imagemagick
apt-get -y install memcached
apt-get -y install munin munin-plugins-extra

# Generate a new root user account and enter it when asked.
apt-get -y install mysql-server

apt-get -y install nload
apt-get -y install python-software-properties
apt-add-repository ppa:chris-lea/node.js
apt-get update
apt-get -y install nodejs

apt-get -y install php5-cgi php5-cli
apt-get -y install php5-curl php5-dev php5-gd php5-gmp php5-json php5-ldap php5-mcrypt php5-memcache php5-mysql php5-xdebug
