#!/bin/bash
#
# Before running this script, install Ubuntu 12.04 LTS with OpenSSH.
# Manually setup the network interface(s) and SSH authorized_keys (disable password login).
#
# Run this script with SUDO
# sudo ./ubuntu-12-04

apt-get update
apt-get -y upgrade

apt-get -y install apache2-mpm-worker
apt-get -y install git
apt-get -y install htop
apt-get -y install imagemagick
apt-get -y install memcached
apt-get -y install munin munin-plugins-extra
