#!/bin/bash
#
# Before running this script, install Ubuntu 12.04 LTS with OpenSSH.
# Manually setup the network interface(s) and SSH authorized_keys (disable password login).
#
# Do not run this script as sudo
# ./ubuntu-12-04

sudo apt-get update
sudo apt-get -y upgrade

sudo apt-get -y install apache2-mpm-worker
sudo apt-get -y install libapache2-mod-fcgid
sudo a2enmod ssl
sudo a2enmod rewrite
sudo a2enmod fcgid
sudo a2enmod headers
sudo a2dissite default
sudo a2dissite default-ssl
sudo service apache2 restart

sudo apt-get -y install git
sudo apt-get -y install htop
sudo apt-get -y install imagemagick
sudo apt-get -y install memcached
sudo apt-get -y install munin munin-plugins-extra

# Generate a new root user account and enter it when asked.
sudo apt-get -y install mysql-server

sudo apt-get -y install nload
sudo apt-get -y install python-software-properties
sudo apt-add-repository ppa:chris-lea/node.js
sudo apt-get update
sudo apt-get -y install nodejs
sudo apt-get -y install php5-cgi php5-cli
sudo apt-get -y install php5-curl php5-dev php5-gd php5-gmp php5-json php5-ldap php5-mcrypt php5-memcache php5-memcached php-http php5-mysql php5-xdebug
sudo apt-get -y install libpcre3-dev
sudo apt-get -y install libcurl3
sudo apt-get -y install libcurl4-gnutls-dev
sudo pecl install pecl_http-1.7.6
sudo apt-get -y install python3
sudo apt-get -y install dkms
sudo apt-get -y install zip
sudo apt-get -y install redis-server

sudo add-apt-repository ppa:mapnik/boost
wget -O - http://dl.hhvm.com/conf/hhvm.gpg.key | sudo apt-key add -
echo deb http://dl.hhvm.com/ubuntu precise main | sudo tee /etc/apt/sources.list.d/hhvm.list
sudo apt-get update
sudo apt-get install hhvm

sudo apt-get -y install python-pip
sudo pip install slimit

sudo npm -g install bower

cd ~

curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer
sudo hhvm /usr/local/bin/composer self-update

git config --global core.editor nano
git config --global url.https://.insteadOf git://
git config --global push.default current
git config --global color.ui auto
git config --global color.status always

git clone https://github.com/igbinary/igbinary
cd igbinary
phpize
./configure
make
sudo make install
echo extension=igbinary.so | sudo tee /etc/php5/conf.d/igbinary.ini > /dev/null
cd ~

git clone https://github.com/nicolasff/phpredis
cd phpredis
phpize
./configure --enable-redis-igbinary
make
sudo make install
echo extension=redis.so | sudo tee /etc/php5/conf.d/redis.ini > /dev/null
cd ~

git clone git@github.com:myerscough-eteam/bloom.git
cd bloom
git checkout master
make

# From here, it's up to you to manually setup Apache, PHP and MySQL
